#fuel_tech_support_hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: FuelTechSupportBundle:Default:index }
ftsupport_home:
    pattern: /
    defaults: { _controller: FuelTechSupportBundle:Home:index }
ftsupport_client_list:
    pattern: /client
    defaults: { _controller: FuelTechSupportBundle:Client:list }
ftsupport_client_detail:
    pattern: /client/{id}
    defaults: { _controller: FuelTechSupportBundle:Client:showDetail }
    requirements:
        id: \d+
ftsupport_client_new:
    pattern: /client/new
    defaults: { _controller: FuelTechSupportBundle:Client:new }
ftsupport_client_delete:
    pattern: /client/delete/{id}
    defaults: { _controller: FuelTechSupportBundle:Client:delete }
    requirements:
        id: \d+
ftsupport_contact_new:
    pattern: /contact/new/{clientid}
    defaults: { _controller: FuelTechSupportBundle:Contact:new }
    requirements:
        clientid: \d+
ftsupport_contact_delete:
    pattern: /contact/delete/{id}
    defaults: { _controller: FuelTechSupportBundle:Contact:delete }
    requirements:
            id: \d+
ftsupport_contact_detail:
    pattern: /contact/{id}
    defaults: { _controller: FuelTechSupportBundle:Contact:showDetail }
    requirements:
        id: \d+