#fuel_tech_support_hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: FuelTechSupportBundle:Default:index }
ftsupport_home:
    pattern: /
    defaults: { _controller: FuelTechSupportBundle:Home:index }
ftsupport_client_list:
    pattern: /client
    defaults: { _controller: FuelTechSupportBundle:Client:index }
ftsupport_client_detail:
    pattern: /client/{id}
    defaults: { _controller: FuelTechSupportBundle:Client:showDetail }
    requirements:
        id: \d+
ftsupport_contact_detail:
    pattern: /contact/{id}
    defaults: { _controller: FuelTechSupportBundle:Contact:showDetail }
    requirements:
        id: \d+