fuel_tech_support_hello:
    pattern:  /hello/{name}
    defaults: { _controller: FuelTechSupportBundle:Default:index }
fuel_tech_support_hello:
    pattern: /
    defaults: { _controller: FuelTechSupportBundle:Home:index }