parameters:
#    fuel_tech_support.example.class: FuelTech\SupportBundle\Example

services:
#    fuel_tech_support.example:
#        class: %fuel_tech_support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
