FuelTech\SupportBundle\Entity\Contact:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        telephone:
            type: string
            length: 15
            nullable: true
        mobile:
            type: string
            length: 15
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: contacts
            joinColumn:
                name: client_id
                referencedBy: id
                onDelete: cascade
    lifecycleCallbacks: {  }
